# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:19:10+00:00



import argparse
import json
import os
from typing import *

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Path

from models import ApiResponse, Findings, ScanDefinition

app = MCPProxy(
    contact={'email': 'getsupport@patrowl.io', 'x-twitter': 'patrowl_io'},
    description='This is the API documentation for Patrowl Engines usage.',
    license={
        'name': 'Apache 2.0',
        'url': 'http://www.apache.org/licenses/LICENSE-2.0.html',
    },
    title='Swagger API-REST for Patrowl Engines',
    version='1.0.0',
    servers=[
        {'url': 'http://patrowl.local'},
        {'url': 'http://localhost:5001/engines/nmap/'},
        {'url': 'http://localhost:5004/engines/ssllabs/'},
        {'url': 'http://localhost:5005/engines/arachni/'},
        {'url': 'http://localhost:5006/engines/owl_dns/'},
        {'url': 'http://localhost:5007/engines/virustotal/'},
        {'url': 'http://localhost:5008/engines/urlvoid/'},
        {'url': 'http://localhost:5009/engines/cortex/'},
        {'url': 'http://localhost:5012/engines/owl_leaks/'},
        {'url': 'http://localhost:5013/engines/owl_code/'},
        {'url': 'http://localhost:5014/engines/sslscan/'},
    ],
)


@app.get(
    '/#-datamodel-code-generator-#-root-#-special-#',
    description=""" Return index page """,
    tags=['page_navigation'],
)
def get_default_page():
    """
    Index page
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/clean', description=""" Clean all current scans. """, tags=['scan_cleanup'])
def clean_scans_page():
    """
    Clean all scans
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/clean/{scanId}',
    description=""" Clean scan identified by id. """,
    tags=['scan_cleanup'],
)
def clean_scan_page(scan_id: int = Path(..., alias='scanId')):
    """
    Clean scan
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/getfindings/{scanId}',
    description=""" Get findings on finished scans. """,
    tags=['scan_findings'],
)
def get_finding_page(scan_id: int = Path(..., alias='scanId')):
    """
    Get findings on finished scans
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/info', description=""" Return information on engine. """, tags=['page_navigation']
)
def get_info_page():
    """
    Engine info page
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/liveness', description=""" Return liveness page """, tags=['page_navigation']
)
def get_liveness_page():
    """
    Liveness page
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/readiness', description=""" Return liveness page """, tags=['page_navigation']
)
def get_readiness_page():
    """
    Readiness page
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/reloadconfig',
    description=""" Reload the configuration file. """,
    tags=['configuration_management'],
)
def reload_configuration_page():
    """
    Configuration reloading page
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/startscan', description=""" Start a new scan. """, tags=['scan_management'])
def start_scan_page(body: ScanDefinition):
    """
    Start a new scan
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/status', description=""" Status all current scans. """, tags=['scan_management']
)
def status_scans_page():
    """
    Status on all scans
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/status/{scanId}',
    description=""" Status of a scan identified by id. """,
    tags=['scan_management'],
)
def status_scan_page(scan_id: int = Path(..., alias='scanId')):
    """
    Status of a scan
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/stop/{scanId}',
    description=""" Stop a scan identified by id. """,
    tags=['scan_management', 'scan_cleanup'],
)
def stop_scan_page(scan_id: int = Path(..., alias='scanId')):
    """
    Stop a scan
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/stopscans',
    description=""" Stop all current scans. """,
    tags=['scan_management', 'scan_cleanup'],
)
def stop_scans_page():
    """
    Stop all scans
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/test', description=""" Return test page """, tags=['page_navigation'])
def get_test_page():
    """
    Test page
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
