# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:19:10+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel


class ApiResponse(BaseModel):
    page: Optional[str] = None
    status: Optional[str] = None


class MetaRisk(BaseModel):
    cvss_base_score: Optional[List[str]] = None
    cvss_vector: Optional[List[str]] = None
    exploit_available: Optional[List[str]] = None
    exploitability_ease: Optional[List[str]] = None
    patch_publication_date: Optional[List[str]] = None


class MetaVulnRefs(BaseModel):
    bid: Optional[List[str]] = None
    cpe: Optional[List[str]] = None
    cve: Optional[List[str]] = None
    cwe: Optional[List[str]] = None


class Severity(Enum):
    info = 'info'
    low = 'low'
    medium = 'medium'
    high = 'high'


class Finding(BaseModel):
    confidence: Optional[str] = None
    description: Optional[str] = None
    issue_id: Optional[int] = None
    meta_links: Optional[List[str]] = None
    meta_risk: Optional[MetaRisk] = None
    meta_tags: Optional[List[str]] = None
    meta_vuln_refs: Optional[MetaVulnRefs] = None
    raw: Optional[str] = None
    severity: Optional[Severity] = None
    solution: Optional[str] = None
    target_addrs: Optional[List[str]] = None
    target_proto: Optional[List[str]] = None
    timestamp: Optional[datetime] = None
    title: Optional[str] = None
    type: Optional[str] = None


class Findings(RootModel[List[Finding]]):
    root: List[Finding]


class Criticity(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class Datatype(Enum):
    ip = 'ip'
    ip_range = 'ip-range'
    ip_subnet = 'ip-subnet'
    fqdn = 'fqdn'
    domain = 'domain'
    url = 'url'
    keyword = 'keyword'
    person = 'person'
    organisation = 'organisation'
    path = 'path'
    application = 'application'


class Asset(BaseModel):
    criticity: Optional[Criticity] = None
    datatype: Optional[Datatype] = None
    id: Optional[str] = Field(None, examples=['3'])
    value: Optional[str] = Field(None, examples=['8.8.8.8'])


class ScanDefinition(BaseModel):
    assets: Optional[List[Asset]] = None
    options: Optional[Dict[str, Any]] = None
    scan_id: Optional[int] = Field(None, examples=[1])
